name: redstone_web_socket
version: 0.1.0
description: A web socket plugin for Redstone.dart
author: Luiz Mineo <luiz.mineo@gmail.com>
homepage: http://redstonedart.org
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  redstone: ^0.6.7
  shelf_web_socket: ^0.2.1
  di: ^3.3.10
dev_dependencies:
  test: ^0.12.0
